const merchandise = [
    {
        materialName: "Material A",
        materialId: 1,
        Unit: "PCS",
        materialClassId: "Bao bì",
        MinimumStockLevel: 50,
        DefaultStockLevel: 100,
        PacketSize: "10x10",
        Price: 500,
        Note: "High quality material A",
    },
    {
        materialName: "Material B",
        materialId: 2,
        Unit: "PCS",
        materialClassId: "Bao bì",
        MinimumStockLevel: 20,
        DefaultStockLevel: 50,
        PacketSize: "5x5",
        Price: 200,
        Note: "Standard material B",
    },
    {
        materialName: "Material C",
        materialId: 3,
        Unit: "PCS",
        materialClassId: "Bao bì",
        MinimumStockLevel: 30,
        DefaultStockLevel: 60,
        PacketSize: "20x20",
        Price: 300,
        Note: "Durable material C",
    },
    {
        materialName: "Material D",
        materialId: 4,
        Unit: "PCS",
        materialClassId: "Bao bì",
        MinimumStockLevel: 10,
        DefaultStockLevel: 25,
        PacketSize: "15x15",
        Price: 150,
        Note: "Compact material D",
    },
    {
        materialName: "Material E",
        materialId: 5,
        Unit: "PCS",
        materialClassId: "Bao bì",
        MinimumStockLevel: 40,
        DefaultStockLevel: 80,
        PacketSize: "30x30",
        Price: 400,
        Note: "Flexible material E",
    },
    {
        materialName: "Material F",
        materialId: 6,
        Unit: "PCS",
        materialClassId: "Bao bì",
        MinimumStockLevel: 15,
        DefaultStockLevel: 35,
        PacketSize: "25x25",
        Price: 250,
        Note: "Reliable material F",
    },
    {
        materialName: "Material G",
        materialId: 7,
        Unit: "PCS",
        materialClassId: "Bao bì",
        MinimumStockLevel: 60,
        DefaultStockLevel: 120,
        PacketSize: "40x40",
        Price: 600,
        Note: "Premium material G",
    },
    {
        materialName: "Material H",
        materialId: 8,
        Unit: "PCS",
        materialClassId: "Bao bì",
        MinimumStockLevel: 25,
        DefaultStockLevel: 55,
        PacketSize: "35x35",
        Price: 350,
        Note: "Efficient material H",
    },
    {
        materialName: "Material I",
        materialId: 9,
        Unit: "PCS",
        materialClassId: "Bao bì",
        MinimumStockLevel: 45,
        DefaultStockLevel: 90,
        PacketSize: "50x50",
        Price: 450,
        Note: "Eco-friendly material I",
    },
    {
        materialName: "Material J",
        materialId: 10,
        Unit: "PCS",
        materialClassId: "Bao bì",
        MinimumStockLevel: 35,
        DefaultStockLevel: 70,
        PacketSize: "45x45",
        Price: 700,
        Note: "High-grade material J",
    },
];

export default merchandise;